### ISSUE TITLE
Bincode 2-alpha.0 checklist

### ISSUE THREAD

**Issue by VictorKoenders** [bincode-org/bincode#411]
- [x] Make bincode able to run without dependencies (#409)
- [x] Implement Encodeable/Decodeable on the following types:
  - [x] Basic types: bool, char
  - [x] Compound types: tuples (up to 8 for now)
  - [x] Common core types: `Option<T>`, `Result<V, E>`, `Cell<T>`, `RefCell<T>`
  - [x] Less common core types:  `Duration`, `Range<T>`, `RangeInclusive<T>`, `Bound<T>`, `NonZero*`
  - [x] Wrapper types: `Box<T>`, `Box<[T]>`, `Box<str>`, `Cow<'a, T>`, `Rc<T>`, `Arc<T>`
  - [x] Collections: `BTreeMap<K, V>`, `BTreeSet<T>`, `BinaryHeap<T>`, `HashMap<K, V>`, `HashSet<T>`, `VecDeque<T>`, `Vec<T>`
  - [x] FFI types: `CString`, `Box<CStr>`,  `&CStr`
  - [x] Misc std types: `Mutex`, `RwLock`, `SystemTime`, `Path`, `PathBuf`
  - [x] Net types: `IpAddr`, `Ipv4Addr`, `Ipv6Addr`, `SocketAddr`, `SocketAddrV4`, `SocketAddrV6`
  - [x] Atomic types (behind a feature flag, some platforms like cortex-m0 don't support atomics)
- [ ] Implement encode/decode functions for the following types:
  - [x] `&mut [u8]` / `&[u8]`
  - [x] `Vec<u8>` / -
  - [x] `std::io::Write` / `std::io::Read`
  - [ ] `serde::ser::Serialize` / `serde::de::Deserialize`
- [ ] Settle on names for the bincode 1 config and bincode 2 config
- [x] Review trait names

(Work is being done in the [feature/deserde](https://github.com/bincode-org/bincode/tree/feature/deserde) branch)

**Comment by VictorKoenders** [comment]
Updated Encodeable/Decodeable list based on https://docs.rs/serde/1.0.130/serde/de/index.html#implementations-of-deserialize-provided-by-serde

**Comment by VictorKoenders** [comment]
Not going to support `OsStr` and `OsString` for now, serde does some dirty internal hacks and I'm not sure how many people use it
https://github.com/serde-rs/serde/blob/72060b779a6411800f0e7052898133539b6b4713/serde/src/de/impls.rs#L1610-L1677

**Comment by VictorKoenders** [comment]
Bincode 2.0-alpha.0 is released!

https://docs.rs/bincode/2.0.0-alpha.0/bincode
