### ISSUE TITLE
Bincode 2 updated documentation

### ISSUE THREAD

**Issue by VictorKoenders** [bincode-org/bincode#436]
Some things that I need to document

- [x] Document implementing `Decode` and `Encode` manually #480 
- [x] List of config options to use for max compression/performance/etc #480 
- [x] `See Config for more information on the configuration options.` needs to point to `Configuration` #480 
- [ ] ~~Best practice of adding `const CONFIG: Configuration = Configuration::standard().with_xxx();` to your binary~~
- [x] Make docs consistent about fixed-size array length encoding #480 
- [x] Fix `Decoder::config()` incorrectly reporting it returns a mutable reference #480 
- [x] Migration guide #482

**Comment by jrose-signal** [comment]
The docs are also currently inconsistent about whether a fixed-size array is encoded with its length or not. I see that that's a configuration option now, so probably both places that mention it need to be updated!

**Comment by ghost** [comment]
https://docs.rs/bincode/2.0.0-beta.0/bincode/de/trait.Decoder.html#tymethod.config

The doc wording here talks about a mutable reference but it gives a &Self::C

**Comment by yujqiao** [comment]
What about the migration guide? I'm curious about bincode v2's departure from serde and don't know if I should upgrade. It will be helpful to see documentation and the motivation of bincode v2.

**Comment by VictorKoenders** [comment]
> What about the migration guide? 

Migrating with `serde` should be simple, enable the `serde` feature and use the functions in `bincode::serde`.

A bigger write-up in #482
