### ISSUE TITLE
[Tracking issue] removing `unsafe` implementations copied from `core`

### ISSUE THREAD

**Issue by VictorKoenders** [bincode-org/bincode#536]
- [ ] maybe_uninit_slice https://github.com/rust-lang/rust/issues/63569
- [ ] maybe_uninit_uninit_array (no tracking issue)
- [ ] maybe_uninit_array_assume_init https://github.com/rust-lang/rust/issues/80908

**Comment by ghost** [comment]
https://github.com/rust-lang/rust/issues/80908 is closed now
